## Aporeto
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/aporeto-inc/domingo"
  version = "3.25.0"

[[constraint]]
  name = "github.com/aporeto-inc/regolithe"
  version = "1.x"

[[constraint]]
  name = "github.com/magefile/mage"
  version = "2.0.1"

## Third Party
[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[prune]
  go-tests = true
  unused-packages = true
